export const EDIT_HISTORY_COPY = {
  screenTitle: 'Өзгерістер тарихы',
  screenSubtitle: 'Кім не өзгертті — барлығы осында сақталады',
  emptyTitle: 'Әлі өзгеріс жоқ',
  emptySubtitle: 'Туыс немесе естелік өзгертілгенде, тарих осында көрінеді',
  restore: 'Қалпына келтіру',
  restoreSuccess: 'Бұрынғы нұсқа қалпына келтірілді',
  restoreBlocked: 'Бұл өзгерісті қалпына келтіру мүмкін емес',
  restoreConfirmTitle: 'Бұрынғы нұсқаны қалпына келтіреміз бе?',
  restoreConfirmHint:
    'Ағымдағы деректердің орнына таңдалған нұсқа қойылады. Бұл әрекет тарихқа жазылады.',
  saveConfirmTitle: 'Өзгерісті сақтаймыз ба?',
  saveConfirmHint: 'Сақталған соң кім өзгерткені тарихта сақталады.',
  cancel: 'Болдырмау',
  save: 'Сақтау',
  actorLine: (name: string) => `${name} өзгертті`,
  ownershipLine: (name: string, when: string) => `Соңғы өзгерту: ${name} · ${when}`,
  actionCreate: 'Қосылды',
  actionUpdate: 'Өзгертілді',
  actionDelete: 'Жойылды',
  actionRestore: 'Қалпына келтірілді',
  relativeLabel: 'Туыс',
  memoryLabel: 'Естелік',
  viewHistory: 'Тарихты көру',
  managementTitle: 'Өзгерістер тарихы',
  managementSubtitle: 'Қалпына келтіру · кім өзгертті',
} as const;
