import { kk, FAMILY_LANGUAGE } from '@/content/family-language';

export const FAMILY_MEMORIES_COPY = {
  screenTitle: kk(FAMILY_LANGUAGE.memories.screenTitle),
  screenSubtitle: kk(FAMILY_LANGUAGE.memories.screenSubtitle),
  addTitle: kk(FAMILY_LANGUAGE.memories.addTitle),
  addSubtitle: kk(FAMILY_LANGUAGE.memories.addSubtitle),
  save: kk(FAMILY_LANGUAGE.memories.save),
  saving: kk(FAMILY_LANGUAGE.memories.saving),
  saved: kk(FAMILY_LANGUAGE.memories.saved),
  savedHint: kk(FAMILY_LANGUAGE.memories.savedHint),
  recentTitle: kk(FAMILY_LANGUAGE.memories.recentTitle),
  recentHint: kk(FAMILY_LANGUAGE.memories.recentHint),
  emptyPromptTitle: kk(FAMILY_LANGUAGE.memories.emptyPromptTitle),
  emptyPromptHint: kk(FAMILY_LANGUAGE.memories.emptyPromptHint),
  seeAll: kk(FAMILY_LANGUAGE.memories.seeAll),
  profileTitle: kk(FAMILY_LANGUAGE.memories.profileTitle),
  profileHint: kk(FAMILY_LANGUAGE.memories.profileHint),
  profileEmptyTitle: kk(FAMILY_LANGUAGE.memories.profileEmptyTitle),
  profileEmptyHint: kk(FAMILY_LANGUAGE.memories.profileEmptyHint),
  profileAdd: kk(FAMILY_LANGUAGE.memories.profileAdd),
  profileSeeAll: kk(FAMILY_LANGUAGE.memories.profileSeeAll),
  deleteConfirmTitle: kk(FAMILY_LANGUAGE.memories.deleteConfirmTitle),
  deleteConfirmHint: kk(FAMILY_LANGUAGE.memories.deleteConfirmHint),
  deleteAction: kk(FAMILY_LANGUAGE.memories.deleteAction),
  cancelAction: kk(FAMILY_LANGUAGE.memories.cancelAction),
  types: {
    photo: kk(FAMILY_LANGUAGE.memories.typePhoto),
    story: kk(FAMILY_LANGUAGE.memories.typeStory),
    note: kk(FAMILY_LANGUAGE.memories.typeNote),
  },
  form: {
    type: kk(FAMILY_LANGUAGE.memories.formType),
    title: kk(FAMILY_LANGUAGE.memories.formTitle),
    titlePlaceholder: kk(FAMILY_LANGUAGE.memories.formTitlePlaceholder),
    relative: kk(FAMILY_LANGUAGE.memories.formRelative),
    relativeEmpty: kk(FAMILY_LANGUAGE.memories.formRelativeEmpty),
    story: kk(FAMILY_LANGUAGE.memories.formStory),
    storyPlaceholderStory: kk(FAMILY_LANGUAGE.memories.formStoryPlaceholderStory),
    storyPlaceholderNote: kk(FAMILY_LANGUAGE.memories.formStoryPlaceholderNote),
    storyPlaceholderPhoto: kk(FAMILY_LANGUAGE.memories.formStoryPlaceholderPhoto),
    photo: kk(FAMILY_LANGUAGE.memories.formPhoto),
    photoAdd: kk(FAMILY_LANGUAGE.memories.formPhotoAdd),
    photoChange: kk(FAMILY_LANGUAGE.memories.formPhotoChange),
    photoRemove: kk(FAMILY_LANGUAGE.memories.formPhotoRemove),
    year: kk(FAMILY_LANGUAGE.memories.formYear),
  },
} as const;
