export const USER_IDENTITY_COPY = {
  screenTitle: 'Сіз кімсіз? · Кто вы?',
  intro:
    'Қолданбадағы сіз бен шежіредегі тұлға — әртүрлі нәрсе. Алдымен өзіңізді шежіреден таңдаңыз.',
  existingOption: 'Мен шежіреде бармын · Я уже есть в шежіре',
  existingHint: 'Тізімнен өзіңізді таңдаңыз',
  addOption: 'Мені қосу · Добавить меня',
  addHint: 'Жаңа туыс профилін құрып, оны өзіңізге байлаңыз',
  pickSelfTitle: 'Өзіңізді таңдаңыз · Select yourself',
  pickSelfHint: 'Бұл шежіредегі сіз · not the app login account',
  saveButton: 'Мен — осы адам · This is me',
  saveHint: 'Save linked relative for this device',
  backToOptions: '← Басқа нұсқа таңдау',
  savedTitle: 'Сіз шежіреге байландыңыз 🌿',
  savedMessage: (name: string) => `${name} — енді сіздің шежіре профиліңіз`,
  settingsButton: 'Мен кіммін? · Кто я?',
  settingsHint: 'Change linked shezhire profile',
  onboardingPrompt: 'Алдымен өзіңізді шежіреден таңдаңыз',
  onboardingSubtext: 'Select yourself in the family tree · Сіз кімсіз?',
  openWhoAmI: 'Таңдау · Choose',
  currentLinked: (name: string) => `Қазір байланған: ${name} · Current linked profile`,
  linkedLabel: 'Шежіре профилі · Shezhire profile',
  notLinked: 'Таңдалмаған · Not linked yet',
} as const;
